//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.21 at 04:43:56 PM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://szkolenia.comarch.com/soap/provider/countries")
package com.comarch.szkolenia.soap.client.countries.api;
